[package]
name = "validators"
version = "0.4.4"
authors = ["Magic Len <len@magiclen.org>"]
repository = "https://github.com/magiclen/validators"
homepage = "https://magiclen.org/validators"
keywords = ["validator", "validation", "user", "valid", "input"]
categories = ["value-formatting"]
description= "A library for validating user input."
readme = "README.md"
license = "MIT"

[badges]
travis-ci = { repository = "magiclen/validators", branch = "master" }
appveyor = { repository = "magiclen/validators", branch = "master", service = "github" }

[dependencies]
regex = "1.0.4"
rocket = { version = "0.3.16", optional = true }

[dev-dependencies]
rocket_codegen =  "0.3.16"

[features]
nightly = []
rocketly = ["nightly", "rocket"]